--Set Colours
term.setPaletteColour(colours.black,0x000F1C)
term.setPaletteColour(colours.lime,0x0DDA85)
term.setBackgroundColor(colours.black)
term.setTextColour(colours.lime)
shell.run("clear")

--Print text centred
local function printCentered(text)
 local w, _ = term.getSize()
 local padding = math.floor((w - #text) / 2)
 term.clearLine()
 term.setCursorPos(padding + 1, select(2, term.getCursorPos()))
 print(text)
end
--Get User
local username

if fs.exists("user.txt") then
 local f = fs.open("user.txt", "r")
 username = f.readAll()
 f.close()
else
  textutils.slowPrint("^^^^PIP-OS(R) V3.2.0.0^^^^")
  textutils.slowWrite("Enter User: ")
 username = read()  -- user types their username
 
 local f = fs.open("user.txt", "w")
 f.write(username)
 f.close()
 os.reboot()
end

--Print Information
textutils.slowPrint("^^^^PIP-OS(R) V3.2.0.0^^^^")
print("")
print("")
os.sleep(0.2)
textutils.slowPrint("COPYRIGHT 2075 ROBCO(R)")
os.sleep(0.2)
textutils.slowPrint("LOADER V1.1")
os.sleep(0.2)
textutils.slowPrint("EXEC VERSION 41.10")
os.sleep(0.2)
textutils.slowPrint("64K RAM SYSTEM")
os.sleep(0.2)
write(fs.getFreeSpace("/"))
textutils.slowPrint(" BYTES FREE")
os.sleep(0.2)
textutils.slowPrint("NO HOLOTAPE FOUND")
os.sleep(0.2)
textutils.slowPrint("LOAD ROM(1): DEITRIX 303")

function scroll()
os.sleep(0.05)
print("")
os.sleep(0.05)
print("")
os.sleep(0.05)
print("")
os.sleep(0.05)
print("")
end
scroll()
scroll()
scroll()
scroll()
print("Initializing...")
scroll()
scroll()
os.sleep(1)
term.clear()
print("  +--------------------+")
print("  |                    |")
print("")
print("")
print("")
print("")
print("     Pip-Boy assigned")
print("            to")
printCentered(username)
print("")
print("  |                    |")
print("  +--------------------+")
print("")
print("")
print("")
os.sleep(1)
shell.run("pip-boy/stat.lua")
